version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install filesystem
                command: |
                    source activate filesystem-env
                    python setup.py install
            - run:
                name: Test autoinf
                command: |
                    source activate filesystem-env
                    cd autoinf
                    pytest -v --cov=autoinf --pyargs autoinf
                    flake8 --exit-zero autommol
                    pylint --rcfile=../.pylintrc autoinf
            - run:
                name: Test autofile
                command: |
                    source activate filesystem-env
                    cd autofile
                    pytest -v --cov=autofile --pyargs autofile
                    flake8 --exit-zero autommol
                    pylint --rcfile=../.pylintrc autofile
            - run:
                name: Test autodir
                command: |
                    source activate filesystem-env
                    cd autodir
                    pytest -v --cov=autodir --pyargs autodir
                    flake8 --exit-zero autommol
                    pylint --rcfile=../.pylintrc autodir
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
